version: "3"
services:
  legacy-consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile-legacy
    networks:
      - wikiflow-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 8000M
        reservations:
          cpus: '1'
          memory: 8000M
networks:
  wikiflow-network:
    external:
      name: wikiflow-network